extends Node2D
## Test scene for blob terrain system

@onready var blob_terrain: Node2D = $BlobTerrain


func _ready() -> void:
	# Wait for nodes to be ready
	await get_tree().process_frame

	# Define terrain using ASCII art
	# . = dirt, # = grass
	var ascii_map := """
....................
....###.......###...
...#####.....#####..
...#####.....#####..
....###.......###...
....................
.........##.........
........####........
.......######.......
........####........
.........##.........
....................
....##########......
...############.....
....##########......
....................
"""

	# Load and render
	blob_terrain.load_from_ascii(ascii_map)
	blob_terrain.render()

	print("Blob terrain rendered!")
	print("Map size: ", blob_terrain.map_width, "x", blob_terrain.map_height)
